/*
 * HmSplitTextFileBySize v1.0.6.4
 *
 * Copyright (c) 2024 Akitsugu Komiyama
 * under the MIT License
 */

hidemaruversion "9.25.99";

setcompatiblemode 0x08000000; // マクロ内変数を他と共用しない。

jsmode "WebView2\\HmSplitTextFileBySize";

js {

    let nDivFileKiroByteSize = 1; // 1キロバイトごとにファイルを分割する (0.3など少数もOK)

    hidemaru.postExecMacroFile( currentmacrodirectory() + "\\" + "HmSplitTextFileBySize.main.mac", nDivFileKiroByteSize );
}

